#!/usr/bin/env python3
"""Rebuild data.js — the file:// fallback bundle for the UPSC application.

upsc.html loads the three JSON files over HTTP when served over a network.
When the project is opened directly from disk (file://), fetch() is not
available, so the app falls back to window.UPSC_QUESTION_BANK_DATA which is
provided by this generated bundle.

The bundle is a byte-stable, compact JSON serialisation of:

    data/prelims.json   Prelims GS Paper I (1995-2026)
    data/csat.json      CSAT Paper II      (2011-2026)
    data/mains.json     Mains papers       (2011-2025)

Usage:
    python scripts/build_data_bundle.py

Exit code 0 on success, 1 if a dataset is missing or invalid.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BANNER = "/* Auto-generated by scripts/build_data_bundle.py. */"
DATASETS = ("prelims", "csat", "mains")


def count_questions(name: str, data) -> int:
    if name == "prelims":
        return sum(len(v) for v in data.get("records_by_year", {}).values())
    if name == "csat":
        return len(data.get("questions", []))
    return sum(
        len(packet.get("questions", []))
        for papers in data.get("papers_by_year", {}).values()
        for packet in papers.values()
    )


def main() -> int:
    bundle = {}
    for name in DATASETS:
        path = ROOT / "data" / f"{name}.json"
        if not path.exists():
            print(f"error: missing dataset {path}", file=sys.stderr)
            return 1
        try:
            bundle[name] = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            print(f"error: {path} is not valid JSON: {exc}", file=sys.stderr)
            return 1

    payload = json.dumps(bundle, ensure_ascii=False, separators=(",", ":"))
    out_path = ROOT / "data.js"
    out_path.write_text(
        f"{BANNER}\nwindow.UPSC_QUESTION_BANK_DATA={payload};\n",
        encoding="utf-8",
    )

    print(f"wrote {out_path.relative_to(ROOT)} ({out_path.stat().st_size:,} bytes)")
    total = 0
    for name in DATASETS:
        count = count_questions(name, bundle[name])
        total += count
        print(f"  {name}: {count:,} questions")
    print(f"  total: {total:,} question records")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
